CAR_CARDS_PER_PAGE = 3
CAR_LAST_TRANSACTIONS_PAGES_NUMBER = 20

MAIN_PAGE_CONFIG_FILENAME = 'car_resale_business_project/config/main_page_config.json'
OLAP_CUBES_EXPORT_METRICS_PER_ROW_NO = 6
BOOTSTRAP_GRID_COLUMNS_NO = 12
FILL_OLTP_DB_SLIDER_STEP = 100